import { test,expect } from '@playwright/test';

test('offline study → live solve → comparison → educational views → frozen TEST evaluation',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 const externalRequests:string[]=[];
 await page.route('**/*',route=>{
  const host=new URL(route.request().url()).hostname;
  if(host==='localhost'||host==='127.0.0.1') return route.continue();
  externalRequests.push(route.request().url());
  return route.abort();
 });
 await page.goto('/overview');
 await expect(page.getByRole('heading',{name:'GasOps',exact:true})).toBeVisible();
 await page.screenshot({path:'../output/playwright/01-overview.png',fullPage:true});
 await page.getByRole('link',{name:'Optimization lab',exact:false}).first().click();
 await expect(page.getByRole('heading',{name:'Optimization lab',exact:true})).toBeVisible();
 await page.getByLabel('Lambda',{exact:true}).fill('0');
 await page.getByRole('button',{name:'Run optimization',exact:true}).click();
 await expect(page.getByText(/^(Live solve|Cached live solve) · optimal$/)).toBeVisible();
 await expect(page.getByRole('table',{name:'Optimal schedule'})).toBeVisible();
 await page.getByRole('button',{name:/Light λ = 0.05/}).click();
 await page.getByRole('button',{name:'Run optimization',exact:true}).click();
 await expect(page.getByText(/λ = 0.05 · α = 0.95/)).toBeVisible();
 await page.getByRole('button',{name:'Compare schedules',exact:true}).click();
 await expect(page.getByTestId('comparison-summary')).toContainText('11');
 await page.getByLabel('Show changed transactions only').check();
 await expect(page.getByRole('table',{name:'Optimal schedule'}).getByRole('row')).toHaveCount(12);
 await page.getByRole('button',{name:'treasury_02 slot 4 assigned'}).click();
 await expect(page.getByLabel('Transaction inspector')).toContainText('TX-02');
 await page.screenshot({path:'../output/playwright/02-optimizer-comparison.png',fullPage:true});
 await page.getByRole('button',{name:'Close inspector'}).click();
 await page.getByRole('button',{name:'Evaluate frozen schedule on TEST',exact:true}).click();
 await expect(page.getByRole('heading',{name:'Frozen TEST evaluation',exact:true})).toBeVisible();
 await expect(page.getByRole('note')).toContainText('4.50');
 await page.getByRole('link',{name:'Data explorer',exact:true}).click();
 await expect(page.getByRole('heading',{name:'Data explorer'})).toBeVisible();
 await page.getByLabel('Heatmap day').selectOption('2025-03-01');
 await expect(page.getByText(/this entire row is one historical stochastic scenario/)).toContainText('2025-03-01');
 await page.screenshot({path:'../output/playwright/03-data.png',fullPage:true});
 await page.getByRole('link',{name:'Treasury workload',exact:true}).click();
 await page.getByLabel('Search transactions').fill('treasury_29');
 await page.getByRole('button',{name:'treasury_29',exact:true}).click();
 await expect(page.getByLabel('Transaction inspector')).toContainText('595,254');
 await page.getByRole('button',{name:'Close inspector'}).click();
 await page.getByRole('link',{name:'Mathematical model',exact:true}).click();
 await expect(page.locator('.katex').first()).toBeVisible();
 await page.getByRole('button',{name:/Scenario coefficient/,exact:false}).click();
 await expect(page.locator('.calculator')).toContainText('cᵢₜₛ · ETH');
 await expect(page.locator('.katex-error')).toHaveCount(0);
 await page.getByRole('button',{name:/Complete model/}).click();
 await expect(page.getByTestId('complete-model')).toBeVisible();
 await page.screenshot({path:'../output/playwright/09-complete-model.png',fullPage:true});
 await page.getByRole('button',{name:/Matrix form/}).click();
 await expect(page.getByTestId('matrix-formulation')).toContainText('365 × 140');
 await expect(page.getByTestId('matrix-formulation')).toContainText('506 variables / 395 constraints');
 await page.screenshot({path:'../output/playwright/10-matrix-form.png',fullPage:true});
 await page.getByRole('button',{name:/Gradient & Hessian/}).click();
 await expect(page.getByTestId('linear-calculus')).toContainText('zero matrix');
 await expect(page.getByTestId('linear-calculus')).toContainText('do not solve the integer problem');
 await page.getByRole('button',{name:/LP versus MILP/}).click();
 await expect(page.getByText('LP optimum ≤ integer optimum')).toBeVisible();
 await expect(page.locator('.katex-error')).toHaveCount(0);
 await page.screenshot({path:'../output/playwright/04-model.png',fullPage:true});
 await page.getByRole('link',{name:'Risk & CVaR',exact:true}).click();
 await expect(page.getByRole('heading',{name:'Beyond the threshold'})).toBeVisible();
 await expect(page.locator('.regimes button')).toHaveCount(4);
 await page.screenshot({path:'../output/playwright/05-risk.png',fullPage:true});
 await page.getByRole('link',{name:'Scenario explorer',exact:true}).click();
 await page.getByRole('button',{name:'Worst TRAIN day',exact:true}).click();
 await expect(page.getByRole('heading',{name:/2025.*TRAIN/})).toBeVisible();
 await page.getByRole('button',{name:'TEST',exact:true}).click();
 await expect(page.getByRole('note')).toContainText('EVALUATION ONLY');
 await page.getByRole('link',{name:'TEST results',exact:true}).click();
 await expect(page.getByRole('heading',{name:'Frozen schedule results'})).toBeVisible();
 await expect(page.getByRole('note')).toContainText('4.50');
 await expect(page.locator('.results-table')).toContainText('28.47%');
 await page.screenshot({path:'../output/playwright/06-results.png',fullPage:true});
 await page.getByRole('link',{name:'Solver explorer',exact:true}).click();
 await expect(page.getByText(/not the actual HiGHS execution trace/i)).toBeVisible();
 await page.getByRole('button',{name:/Reveal branch/}).click();
 await page.getByRole('button',{name:/Reveal branch/}).click();
 await expect(page.locator('.branch-node')).toHaveCount(5);
 await page.getByRole('button',{name:/x = 1, y = 1/}).click();
 await expect(page.locator('.node-inspector')).toContainText('UB = 5');
 await expect(page.getByTestId('search-space')).toContainText('not feasible schedules');
 await expect(page.locator('.katex-error')).toHaveCount(0);
 await page.evaluate(()=>window.scrollTo(0,0));
 await page.screenshot({path:'../output/playwright/07-solver.png',fullPage:true});
 await page.getByRole('link',{name:'Methodology',exact:true}).click();
 await expect(page.getByRole('heading',{name:'Methodology & limitations'})).toBeVisible();
 await page.setViewportSize({width:1280,height:800});
 await page.goto('/optimizer');
 await expect(page.getByRole('heading',{name:'Optimization lab'})).toBeVisible();
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
 await page.screenshot({path:'../output/playwright/08-laptop.png',fullPage:true});
 await page.route('**/api/v1/optimization/solve',route=>route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({detail:'Live solve failed. Test injection.'})}));
 await page.getByRole('button',{name:'Run optimization',exact:true}).click();
 await expect(page.getByRole('alert')).toContainText('Live solve failed');
 await expect(page.getByRole('button',{name:/View validated Phase 2 result/})).toBeVisible();
 expect(errors).toEqual([]);
 expect(externalRequests).toEqual([]);
});
